### ISSUE TITLE
Setup Django 

### ISSUE THREAD

**Issue by pythongiant** [GlobalTechTalks/hackathon#16]
Setup Django and configure it for the project

**Comment by cvam0000** [comment]
also change the database to mysql and maintain a requirement.txt file and describe about the setup 
like : dependencies , project_name , app name , database ,etc

**Comment by cvam0000** [comment]
create a superuser also and start a app for the user_auth(login /registration/ and logout ).

**Comment by SinghSatbir** [comment]
I would like to work on this issue.

**Comment by uditwapt** [comment]
use "postgresql" as a database instead of MySql

**Comment by cvam0000** [comment]
> use "postgresql" as a database instead of MySql
but mysql is mentioned in readme file

**Comment by utkarsh2102** [comment]
This seems to have been taken care of.
Closing this.
Thanks, @pythongiant.
