### ISSUE TITLE
Setup Angular for website frontend

### ISSUE THREAD

**Issue by AniVerma17** [GlobalTechTalks/hackathon#35]
The task is to set up the required dependencies and configuration for using Angular framework to develop website frontend.

**Comment by be-thomas** [comment]
I could handle that

**Comment by AniVerma17** [comment]
> I could handle that

@thomasb892 Alright then, I'm assigning this to you.

**Comment by ploh007** [comment]
Is this still being done by @thomasb892 if not I'll do a pull request for stubbing this out.

**Comment by tanmaymohan** [comment]
@ploh007 it's still incomplete, you can take this issue :)

**Comment by ploh007** [comment]
Created a pull request to do this

**Comment by ploh007** [comment]
@tanmaymohan Have you had the chance to take a look at the PR?

**Comment by tanmaymohan** [comment]
Seems good...for now

Will be adding more issues as we progress. We have some offline meetings scheduled for that.
